server:
    port: 7788
    servlet:
        context-path: /config
        
spring:
    application:
        name: config-server # 服务名称
    profiles:
        active: native # 设置读取本地配置文件
    cloud:
        client:
            ip-address: 127.0.0.1 # 客户端的IP地址

eureka:
    instance:
        instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name} # 此项用于配置Provider实例ID。大多数时候需要将IP显示在instance-id中，${spring.cloud.client.ip-address}是从Spring Cloud依赖包中导入的配置项，存放了客户端的IP地址。
        ip-address: ${spring.cloud.client.ip-address} # 设置当前实例的IP地址。${spring.cloud.client.ip-address}是从Spring Cloud依赖包中导入的配置项，存放了客户端的IP地址。
        prefer-ip-address: true # 访问路径优先使用IP地址
        status-page-url-path: /${server.servlet.context-path}/info # 定义当前Provider实例状态页面的URL,此选项配置的是相对路径。默认的相对路径为/info。
        health-check-url-path: /${server.servlet.context-path}/health # 定义Provider实例健康检查页面的URL，此选项配置的是相对路径。默认的相对路径为/health。
        lease-expiration-duration-in-seconds: 15 # 租约有效期，即服务续约到期时间（默认为90秒）
        lease-renewal-interval-in-seconds: 5 # 续约时间间隔（默认为30秒）
    client:
        register-with-eureka: true # 注册到eureka服务器。
        fetch-registry: true # 是否去注册中心获取其他服务
        serviceUrl:
            defaultZone: http://${EUREKA_ZONE_HOST:localhost}:7777/eureka/